export const membrii = [
  {
    id: 'YO5PCS',
    name: 'Ciungan Septimiu',
    operator: 'Tibi',
    authorizationClass: 'III',
    authorizationYear: '1980',
    email: 'electroplast94@yahoo.ro',
    phone: '0767-807470',
  },
  {
    id: 'YO5PUR',
    name: 'Gal Francisc',
    operator: 'Oscar',
    authorizationClass: 'III',
    authorizationYear: '2015',
    email: 'yo5pur.oscar@yahoo.com',
    phone: '0722-659915',
  },
  {
    id: 'YO5BOL',
    name: 'Conradi Ernest',
    operator: '',
    authorizationClass: 'III',
    authorizationYear: '1985',
    email: 'yo5bol@yahoo.com',
    phone: '0745293415',
  },
  {
    id: 'YO5CBN – Silent key',
    name: 'Streza Ioan',
    operator: 'Nelu',
    authorizationClass: 'II',
    authorizationYear: '1980',
    email: '',
    phone: '',
  },
  {
    id: 'YO5OIC',
    name: 'Bîscă Ioan',
    operator: ' Ionuț',
    authorizationClass: 'II',
    authorizationYear: '1997',
    email: 'yo5oic@yahoo.com',
    phone: '0740-680356',
  },
  {
    id: 'YO5BET',
    name: 'Canciu Emil',
    operator: '',
    authorizationClass: '',
    authorizationYear: '',
    email: '',
    phone: '',
  },
  {
    id: 'YO5BFJ',
    name: 'Stoicescu Adrian',
    operator: 'Ady',
    authorizationClass: 'I',
    authorizationYear: '1980',
    email: 'yo5bfj@yahoo.com',
    phone: '',
  },
  {
    id: 'YO5GHA',
    name: 'Utea Dan',
    operator: 'Dan',
    authorizationClass: 'I',
    authorizationYear: '1984',
    email: 'yo5gha@yahoo.com',
    phone: '0744-933054',
  },
  {
    id: 'YO5BXI',
    name: 'Dican Tiberiu',
    operator: 'Tibi',
    authorizationClass: 'II',
    authorizationYear: '1974',
    email: 'sabeco2@yahoo.com',
    phone: '0744-599155',
  },
  {
    id: 'YO5ACH',
    name: 'Chira Gligor',
    operator: 'Gligor',
    authorizationClass: 'II',
    authorizationYear: '1963',
    email: '',
    phone: '0724-013101',
  },
  {
    id: 'YO5OMT',
    name: 'Oprea Mihai',
    operator: '',
    authorizationClass: '',
    authorizationYear: '',
    email: '',
    phone: '',
  },
  {
    id: 'YO5DDD',
    name: 'Popa Vasile',
    operator: ' Popic',
    authorizationClass: 'I',
    authorizationYear: '1979',
    email: 'yo5ddd@yahoo.com',
    phone: '0723201367',
  },
  {
    id: 'YO5OKM',
    name: 'Molnar Ladislau',
    operator: ' Geo',
    authorizationClass: 'III',
    authorizationYear: '1997',
    email: 'yo5okm@yahoo.com',
    phone: '0745-525484',
  },
  {
    id: 'YO5OEW',
    name: 'Wegrzynowski Egon',
    operator: 'Egon',
    authorizationClass: 'I',
    authorizationYear: '1994',
    email: 'wyegon@gmail.com',
    phone: '',
  },
  {
    id: 'YO5PEB',
    name: 'Popescu Eugen',
    operator: '',
    authorizationClass: '',
    authorizationYear: '',
    email: '',
    phone: '',
  },
  {
    id: 'YO5OHT',
    name: 'Bortoș Vasile',
    operator: 'Tică',
    authorizationClass: 'III',
    authorizationYear: '1979',
    email: 'yo5oht@yahoo.com',
    phone: ' 0258-854048',
  },
  {
    id: 'YO5DHQ',
    name: 'Hărmănaș Nechifor',
    operator: 'Nichi',
    authorizationClass: 'II',
    authorizationYear: '1982',
    email: 'yo5pfg@gmail.com',
    phone: '',
  },
  {
    id: 'YO5CEA',
    name: 'Cristea Ștefan',
    operator: 'Ștefan',
    authorizationClass: 'I',
    authorizationYear: '1977',
    email: 'yo5cea@yahoo.com',
    phone: '0726-340141',
  },
  {
    id: 'YO5OCE',
    name: 'Comănici Nicolae',
    operator: 'Nicu',
    authorizationClass: 'I',
    authorizationYear: '1970',
    email: 'coma_nic@yahoo.com',
    phone: '0744-225071',
  },
  {
    id: 'YO5CFI',
    name: 'Șerb Mircea',
    operator: 'Mircea',
    authorizationClass: 'I',
    authorizationYear: '1978',
    email: 'yo5cfi@yahoo.co.uk',
    phone: '0744-998322',
  },
  {
    id: 'YO5ODS',
    name: 'Alexoaie Ovidiu',
    operator: 'Ovidiu',
    authorizationClass: 'II',
    authorizationYear: '1993',
    email: 'yo5ods@yahoo.com',
    phone: '0745-366601',
  },
  {
    id: 'YO5OST',
    name: 'Cenușă Antoniu',
    operator: 'Guffy',
    authorizationClass: 'II',
    authorizationYear: '1984',
    email: 'yo5ost@yahoo.com',
    phone: '0744-801231',
  },
  {
    id: 'YO5OWF',
    name: 'Buda Alexandru',
    operator: '',
    authorizationClass: '',
    authorizationYear: '',
    email: '',
    phone: '',
  },
];
